### DISCUSSION TITLE
AdminLTE v4 Started

### DISCUSSION THREAD

**Discussion by danny007in** [ColorlibHQ/AdminLTE#3294] [General]
From scratch
Follow on https://github.com/ColorlibHQ/AdminLTE/tree/v4-dev

**Comment by danny007in** [comment]
Follow at https://github.com/danny007in/AdminLTE/tree/v4-dev for version 4

**Comment by danny007in** [comment]
@REJack we can discuss here

**Reply by danny007in** [reply]
create branch for v4

**Reply by REJack** [reply]
I've created a v4-dev branch 😄

**Reply by danny007in** [reply]
I'll create basic required first

**Reply by REJack** [reply]
Ok :D I'll start with the JS mirgration and jQuery removing

**Reply by danny007in** [reply]
and migrate in typescript and use esbuild bundler https://esbuild.github.io/

**Reply by danny007in** [reply]
> 
> 
> Ok :D I'll start with the JS mirgration and jQuery removing

Actully removing 90% of files which is not required for v4

**Reply by REJack** [reply]
the big question is, should we start from scratch and copy the stuff when we need them or migration with the existing code?
the most of the codebase isn't pretty that's why i would recommend start from scratch.

**Reply by danny007in** [reply]
Exactly we are starting from scratch.
Because I reviewed scss and many rules are not used in adminlte v3.

**Reply by danny007in** [reply]
While releasing we can rebase

**Reply by REJack** [reply]
That's what I would do too, you can start with the first steps and I will join in the next days to migrate/move the JS to TS with esbuild 😄

**Comment by danny007in** [comment]
Update workflow to run only master branch PR and v4-dev

**Reply by REJack** [reply]
✔️ done

**Comment by danny007in** [comment]
devSetup for adminlte v4 https://github.com/ColorlibHQ/AdminLTE/commit/122b5ac2270542f9cc778412cedb027542b99893

**Reply by danny007in** [reply]
Layout created without js

![image](https://user-images.githubusercontent.com/50356015/112712124-5f2e5080-8ef3-11eb-8cf7-f6df74dc3c6e.png)

**Reply by danny007in** [reply]
@REJack or @puikinsh - can u create a repo like `adminlte-bootstrap-ui-kit` or `<any name u prefered>-bootstrap-ui-kit` in ColorlibHQ so on this we can add dark mode and customize globally it and we can import it to AdminLTE v4
like https://github.com/themesberg/volt-bootstrap-5-dashboard uses https://github.com/themesberg/pixel-bootstrap-ui-kit

**Reply by REJack** [reply]
Where you see that Volt uses Pixel?

**Reply by danny007in** [reply]
I checked the complete code
it directly copy paste to it
but we can import with benefits of `!default`

**Reply by danny007in** [reply]
> it directly copy paste to it

some values changed like colors

**Reply by danny007in** [reply]
volt created just layout and sidebar
and other was there in pixel itself

**Reply by REJack** [reply]
They look like two independet themes, but it would be interessting if we can create from one "main"-repo a BS5 and a Tailwind version 😄 but I think that's a bit overdone for AdminLTE v4.

**Reply by danny007in** [reply]
> can u create a repo like adminlte-bootstrap-ui-kit or <any name u prefered>-bootstrap-ui-kit

if you did this more benefit will be there,
for example,
 some people won't use AdminLTE but they might like UI kit, 
so on so,
 they are ready to contribute in ui-kit

**Reply by danny007in** [reply]
> 
> 
> They look like two independet themes, but it would be interessting if we can create from one "main"-repo a BS5 and a Tailwind version 😄 but I think that's a bit overdone for AdminLTE v4.

i did not understand

**Reply by REJack** [reply]
How would you split AdminLTE, what you would move to the UI Kit and what you would stay in AdminLTE?

**Reply by danny007in** [reply]
```scss
// basic
@import "bootstrap-variables";
@import "-/ui-kit/variables";
@import "-/bootstrap/variables";
@import "-/bootstrap/bootstrap.scss";

// almost all component will be redisigned like: pagination, card etc. (with dark mode)
@import "-/ui-kit/bootstrap.scss";

// Now adminlte layout
@import "variables";
@import "core";

**Reply by REJack** [reply]
overall AdminLTE itself would the UI Kit and with the Skins you would achieve this too.

but the question is would we able to use the ui-kit without bootstrap too? if yes, we could provide other framework versions too.

**Reply by danny007in** [reply]
> ui-kit without bootstrap too?
yes
```scss
// adminlte.scscs

@import "~ui-kit/node_modules/boot---";
```

**Reply by REJack** [reply]
no I mean without the bootstrap mixins etc 🤣

**Reply by danny007in** [reply]
> other framework versions too

for another framework another ui-kit repo

**Reply by danny007in** [reply]
> 
> 
> no I mean without the bootstrap mixins etc 🤣

ui-kit intension is to modify bootstrap framework according to adminlte

**Reply by danny007in** [reply]
> no I mean without the bootstrap mixins etc 🤣

we required bootstrap mixins in ui-kit but in main adminlte dev we can import in node_modules bootstrap directly

**Reply by REJack** [reply]
I personally would stay with the AdminLTE repo but I would create a new repo for all the new skins like sweetalert did.

**Reply by danny007in** [reply]
> 
> 
> create a new repo for all the new skins like sweetalert did.

exactly that's my point.
we will stay in AdminLTE .
but like color scheme and other UI elements like bootstraps (pagination, cards with darkmode) we can create for it.
something like https://github.com/ForEvolve/bootstrap-dark

**Reply by REJack** [reply]
ok 😄 one repo per skin or all skins in one repo?

**Reply by danny007in** [reply]
> ok 😄 one repo per skin or all skins in one repo?

what u mean by skin exactly, example plz

**Reply by danny007in** [reply]
one repo for skins
with if conditions
```scss
$enable-pagination-skin = true;
```

**Reply by REJack** [reply]
Look at AdminLTE v2 (https://github.com/ColorlibHQ/AdminLTE/tree/v2/dist/css/skins) there was a css/skins folder with all extra skins, I want to bring them back to reduce the css file size again.

**Reply by REJack** [reply]
I also was thinking about to create a skin builder (web app)

**Reply by danny007in** [reply]
> 
> 
> Look at AdminLTE v2 ([`v2`/dist/css/skins](https://github.com/ColorlibHQ/AdminLTE/tree/v2/dist/css/skins)) there was a css/skins folder with all extra skins, I want to bring them back to reduce the css file size again.

I checked we can add that.
along with we can add dark-mode skin

then create repo name as 'adminlte-themes' 

and also create another repo for UI kit because, for dark-mode add universally like https://github.com/ForEvolve/bootstrap-dark , we make this UI kit as works like no bootstrap scss imports in main repo AdminLTE.

**Reply by REJack** [reply]
I will create tomorrow two repos, idk if we should name it AdminLTE-Themes or AdminLTE-Skins 🤣

**Reply by danny007in** [reply]
> I also was thinking about to create a skin builder (web app)

after release of AdminLTE v4
and
now u can create UI kit repo

**Reply by danny007in** [reply]
> idk

as themes

**Reply by danny007in** [reply]
UI-kit to reduce work

```scss

$primary:                     $blue !default;
$primary-inverse:             $white !default;

$secondary:                   $gray-600 !default;
$secondary-inverse:           $white !default;

$tertiary:                    $soft-apricot !default;
$tertiary-inverse:            $white !default;

// Check this carefully
$light:                       $gray-100 !default;
$light-inverse:               $gray-600 !default;

$theme-inverse-colors: () !default;
$theme-inverse-colors: map.merge((
  "primary":    $primary-inverse,
  "secondary":  $secondary-inverse,
  "tertiary":   $tertiary-inverse,
  "success":    $success-inverse,
  "info":       $info-inverse,
  "warning":    $warning-inverse,
  "danger":     $danger-inverse,
  "light":      $light-inverse,
  "dark":       $dark-inverse
), $theme-inverse-colors);

// Theme colors
@each $name, $value in $theme-colors {
  .btn.btn-#{$name} {
    color: theme-inverse-color($name);
  }
  .btn.btn-outline-#{$name}:hover {
    color: theme-inverse-color($name);
  }
}

// function 
@use "sass:map";

@function theme-inverse-color($key: "primary") {
  @return map.get($theme-inverse-colors, $key);
}

```

Final material output:

![image](https://user-images.githubusercontent.com/50356015/112773374-7d12c700-9053-11eb-84a7-b58ae405b2e7.png)
