### ISSUE TITLE
You don't need z-index

### ISSUE THREAD

**Issue by StevenLiekens** [ColorlibHQ/AdminLTE#1394]
The `.main-header` element is given a z-index value of 1030 and `.main-sidebar` is given a z-index value of 810.  Why? I suspect you did this because you had a problem with the height of the sidebar when set to 100%.

I'm here to tell you that **you don't need z-index**.   In fact, it's messing up my modal dialog overlays so please stop using z-index completely.

In your stylesheet, replace this:

```css
.main-header {
  z-index: 1030;
}

.main-sidebar, .left-side {
  top: 0;
  padding-top: 50px;
  min-height: 100%;
  z-index: 810;
}
```

Replace with:

```css
.main-header {
  /* removed z-index */
}

.main-sidebar, .left-side {
  min-height: calc(100%-50px);
  /* removed top */
  /* removed padding-top */
  /* removed z-index */
}
```

Removing the z-index from these elements results in dozens of new styling issues in completely unrelated places. You might say 'well duh', but I'm here to say that this wouldn't have been a problem if you had read [The stacking context](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context) and [Stacking without z-index](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/Stacking_without_z-index) before putting a custom z-index on so many elements.

Regardless, if you cannot change one CSS rule without breaking another, let alone dozens, there is obviously something wrong.

Thanks for understanding
