### ISSUE TITLE
Datepicker not showing months/years correctly

### ISSUE THREAD

**Issue by DiomedesDominguez** [ColorlibHQ/AdminLTE#1592]
In MS Edge (I haven't test it in other browsers), when I click to show the months or the years it doesn't show it like the days.

In the left are the months, in the right are the days.
![ljabsf](https://user-images.githubusercontent.com/4379316/28576126-f9342d8e-7120-11e7-96e5-be8bff2e14b4.png)

Here is the fix for AdminLTE.css, line 4607

```CSS
.box .datepicker-inline, .box .datepicker-inline .datepicker-days, .box .datepicker-inline > table, .box .datepicker-inline .datepicker-days > table, .box .datepicker-inline .datepicker-months, .box .datepicker-inline .datepicker-months > table, .box .datepicker-inline .datepicker-years, .box .datepicker-inline .datepicker-years > table, .box .datepicker-inline .datepicker-decades, .box .datepicker-inline .datepicker-decades > table, .box .datepicker-inline .datepicker-centuries, .box .datepicker-inline .datepicker-centuries > table {
    width: 100%
}
```
