### ISSUE TITLE
v3 - Left sidebar unexpected behavior

### ISSUE THREAD

**Issue by egodsk** [ColorlibHQ/AdminLTE#1860]
### Issue type:
- [ ] Feature request 
- [x] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version:  3.0.0-alpha
* Operating System:  Windows
* Browser (Version):  Chrome (Latest) & Edge

### Description:
In the new v3 (3.0.0-alpha) it looks like the side menu (left) has been change, so that it now includes a scrollbar in order to view all the items available and it scrolls along side you when you scroll in the main content. I do not know if this is expected behavior in the new v3 or a bug- since it had a different behavior in v2. (I testing on Dashboard v1 for both version v2.4 and v3, to see the difference).

(I know that v3 is still in alpha, but from reading about v3, it sounds like your just needed to fix the right sidebar and check which plugins was supported in Bootstrap 4 before you released a beta)

See the attached pictures:
![noscrollbar](https://user-images.githubusercontent.com/18194629/38800887-b2679efe-4168-11e8-8cd3-94fa184f9da7.PNG)
![scrollbar](https://user-images.githubusercontent.com/18194629/38800889-b283b99a-4168-11e8-90c3-74b8bccbf5f3.PNG)

**Comment by Vadimushka** [comment]
The same problem on Google Chrome Version 66.0.3359.181, [see screenshot](http://prntscr.com/jk162x)

**Comment by evandrogrm** [comment]
If you are programming in angular2+ use npmjs.org/overlayscrollbars meanwhile fixed

**Comment by Vadimushka** [comment]
Here is the css code that hides that scroll:
```css
.sidebar {
    padding-bottom: 0;
    padding-top: 0;
    padding-left: .5rem;
    padding-right: .5rem;
    overflow: hidden;
    height: 100vh;
}

.main-sidebar > .sidebar > nav {
    margin-right: -23px;
    padding-right: 22px;
    overflow-y: auto;
    height: calc(100% - 6rem);
}
```
