### ISSUE TITLE
v3 - Layout without sidebar

### ISSUE THREAD

**Issue by marcesdan** [ColorlibHQ/AdminLTE#2095]
I'm trying to rendering a layout without the sidebar, but the layout expect a sidebar to fill the space. How to achieve it?

**Comment by marcesdan** [comment]
I did it by adding

```css
.main-header {
  margin-left: 0;
}
.content-wrapper {
  margin-left: 0;
}
```
