### ISSUE TITLE
Feature request: allow the sandwich menu button to be on the left of the title

### ISSUE THREAD

**Issue by daattali** [ColorlibHQ/AdminLTE#2213]
### Environment:
* AdminLTE Version:  2.0.6
* Operating System:  N/A
* Browser (Version):  N/A

### Description:
Currently, the "sandwich" menu button is always to the right of the title 

![image](https://user-images.githubusercontent.com/952340/63198111-af6edc80-c047-11e9-8d9e-27c0dd732ed6.png)

It would be great if there was an option to easily place the menu on the left instead

**Comment by REJack** [comment]
In my opinion, this would break the layout. But you can change this by yourself with additional css and some html changes.

```css
.logo {
  min-width: 120px; //may this need to be increased with a larger logo mini 
  z-index: 1010;
  position: relative;
}
.logo .sidebar-toggle {
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 0;
  font-size: 14px;
}

.main-header .logo .navbar {
  width: auto;
  margin-left: 0 !important;
  background: none;
  float: left;
}

.main-header .logo .navbar .sidebar-toggle:hover {
  background: inherit;
}

.main-header .logo a{
  color: inherit;
}
.main-header .logo a:hover{
  color: inherit;
}

.logo-lg,
.logo-mini {
   margin-left: 27px;
}
.sidebar-collapse .logo-lg {
  display: none !important;
}
.sidebar-collapse .logo-mini {
  display: block !important;
}
```

```html
<!-- Logo -->
<div class="logo">
  <!-- Sidebar toggle button-->
  <div class="navbar">
    <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
      <span class="sr-only">Toggle navigation</span>
    </a>
  </div>

  <a href="index2.html">
    <!-- mini logo for sidebar mini 50x50 pixels -->
    <span class="logo-mini"><b>A</b>LT</span>
    <!-- logo for regular state and mobile devices -->
    <span class="logo-lg"><b>Admin</b>LTE</span>
  </a>
</div>
```
