### ISSUE TITLE
I want to Hide the sidebar completely(not just collapse) and also stop the hover effect when collapsed

### ISSUE THREAD

**Issue by sangeetmen** [ColorlibHQ/AdminLTE#2224]
### Issue type:
- [x] Feature request 
- [ ] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version:  v3 beta
* Operating System:  Windows
* Browser (Version):  Firefox (Latest)

### Description:
I would like to do two different scenarios.
**First Scenario** On one of the pages I need to 
 Hide the left sidebar completely (not just collapse) and open only when clicked on the `pushmenu` widget

**Second Scenario** I want to show the Collapsed sidebar. But, I want to stop the hover effect on the sidebar. The sidebar should open only when the clicked on the `pushmenu`

**Comment by REJack** [comment]
For the first scenario, you need only to remove `sidebar-mini` from body
For the second scenario, I need to add a custom class for this

**Comment by sangeetmen** [comment]
Your suggestions for the first scenario worked perfectly!!
Any workaround for the second scenario?

**Comment by REJack** [comment]
I've added in my PR #2220 a `.sidebar-no-expand` for the second scenario, you can add this css for a workaround 
```css

.sidebar-collapse .sidebar-no-expand.main-sidebar.sidebar-focused,
.sidebar-collapse .sidebar-no-expand.main-sidebar:hover {
  width: 4.6rem;
}

.sidebar-collapse .sidebar-no-expand.main-sidebar.sidebar-focused .user-panel .image,
.sidebar-collapse .sidebar-no-expand.main-sidebar:hover .user-panel .image {
  float: none !important;
}

.sidebar-collapse .sidebar-no-expand.main-sidebar.sidebar-focused .brand-text,
.sidebar-collapse .sidebar-no-expand.main-sidebar.sidebar-focused .user-panel > .info,
.sidebar-collapse .sidebar-no-expand.main-sidebar.sidebar-focused .nav-sidebar .nav-link p,
.sidebar-collapse .sidebar-no-expand.main-sidebar:hover .brand-text,
.sidebar-collapse .sidebar-no-expand.main-sidebar:hover .user-panel > .info,
.sidebar-collapse .sidebar-no-expand.main-sidebar:hover .nav-sidebar .nav-link p {
  margin-left: -10px;
  opacity: 0;
  visibility: hidden;
  width: 0;
}

.sidebar-collapse .sidebar-no-expand.main-sidebar.sidebar-focused .nav-sidebar > .nav-item .nav-icon,
.sidebar-collapse .sidebar-no-expand.main-sidebar:hover .nav-sidebar > .nav-item .nav-icon {
  margin-right: 0;
}
```
