### ISSUE TITLE
How Increase Adminlte main-header height

### ISSUE THREAD

**Issue by noblemfd** [ColorlibHQ/AdminLTE#2305]
### Issue type:
- [ ] Feature request Requesting the implementation of a new feature
- [ ] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version:  Example: 2.4.15
* Operating System:  Example: Windows
* Browser (Version):   Example: Chrome (Latest)

### Description:

My logo is a bit bigger than the height of Adminlte main-header, and I don't want to distort the height of the logo. 

> I want to add the Logo where AdminLTE is written by the top left

. How do I increase the height of adminlte **main-header**?
 Thanks

![adminlte_mainheader](https://user-images.githubusercontent.com/34077129/66221925-e9637300-e6c7-11e9-802b-da08b85c8f37.PNG)

**Comment by REJack** [comment]
You need to add custom css, it's not hard here is a example.
I've changed height to 70px and increased the padding by 10px for top and bottom, stock padding is 15px.

```css
.main-header .logo {
  height: 70px;
}

.main-header .sidebar-toggle {
  padding-top: 25px;
  padding-bottom: 25px;
}

.main-header .navbar-nav > li > a {
  padding-top: 25px;
  padding-bottom: 25px;
}
```
