### ISSUE TITLE
[FEATURE] sidebar menu bottom left fixed settings bar

### ISSUE THREAD

**Issue by deepak458** [ColorlibHQ/AdminLTE#2441]
@REJack I'm looking for one more link into sidebar menu link. There can be a fix menu inside sidebar menu that appear always on bottom left corner, inside it we can show setting gear menu and few other things like Visual basic code.

Hope you understand what i'm taking about, developers can show there users status like (Online, Offline, Busy). or something else like more settings page link, theme links.

**Comment by REJack** [comment]
Do you mean something like this?
![Screenshot_2019-12-11 AdminLTE 3 Dashboard](https://user-images.githubusercontent.com/1554582/70617910-e5952500-1c11-11ea-9fe3-7254f70600c9.png)

This example would work only with fixed layout.

**Comment by deepak458** [comment]
@REJack yes, that's what i'm taking about you can provide some different background color to it also some `padding` from left and right with `border-top` CSS. If user use mini sidebar that show only gear icon.

**Comment by REJack** [comment]
It use the same padding like the menu items above, to get it in one line. But you can modify it by yourself. I've added also a custom class to hide the "Help" button on collapse. I would add only a border not a background so you can add a background color by yourself too 😄 

```html
  <!-- Main Sidebar Container -->
  <aside class="main-sidebar main-sidebar-custom sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="index3.html" class="brand-link">
      <img src="dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
           style="opacity: .8">
      <span class="brand-text font-weight-light">AdminLTE 3</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      ...
    </div>
    <!-- /.sidebar -->
    <div class="sidebar-custom">
      <a href="#" class="btn btn-link"><i class="fas fa-cogs"></i></a>
      <a href="#" class="btn btn-secondary hide-on-collapse pos-right">Help</a>
    </div>
  </aside>
```

```css
.sidebar-collapse .main-sidebar-custom  .hide-on-collapse {
  display: none;
}

.sidebar-collapse .main-sidebar-custom :hover .hide-on-collapse {
  display: block;
}

.main-sidebar-custom  .sidebar {
  height: calc(100% - 7.6rem);
}

.main-sidebar-custom  .sidebar-custom {
  height: 4rem;
}

.main-sidebar-custom-lg .sidebar {
  height: calc(100% - 9.6rem);
}

.main-sidebar-custom-lg .sidebar-custom {
  height: 6rem;
}

.main-sidebar-custom-xl .sidebar {
  height: calc(100% - 11.6rem);
}

.main-sidebar-custom-xl .sidebar-custom {
  height: 8rem;
}

.sidebar-custom {
  padding: 0.85rem .5rem;
}

.main-sidebar-custom .pos-right,
.main-sidebar-custom-lg .pos-right,
.main-sidebar-custom-xl .pos-right {
  position: absolute;
  right: .5rem;
}

[class*='sidebar-dark'] .sidebar-custom {
  border-top: 1px solid #4f5962;
}

[class*='sidebar-light'] .sidebar-custom {
  border-top: 1px solid #dee2e6;
}
```

I'll add this in v3.1
