### ISSUE TITLE
[BUG]If first element inside .nav-sidebar is a li.nav-header the padding is different to other li.nav-header

### ISSUE THREAD

**Issue by pauldbentley** [ColorlibHQ/AdminLTE#3409]
**Describe the bug**
If first element inside .nav-sidebar is a li.nav-header the padding is different to other li.nav-header.  I often like to use a .nav-header as the first item.

**To Reproduce**
1. Add `<li class="nav-header">TEST</li>` as the first item in the .nav-sidebar

**Expected behavior**
The padding to the left/right should be of the li.nav-header should be 1rem as per all subsequent headers

**Screenshots**
![nav-header](https://user-images.githubusercontent.com/5243982/107854429-a238d680-6e13-11eb-8a4d-1c9f47059059.png)

**Environment (please complete the following information):**
- AdminLTE Version: 3.1.0-rc
- Operating System:  Windows 10
- Browser (Version): Chrome (latest)

**Additional context**
The problem seems to be in [_main-sidebar.scss](https://github.com/ColorlibHQ/AdminLTE/blob/582f958c5b7b6e152279039ec855b194728dfc93/build/scss/_main-sidebar.scss#L182)

```css
.nav-header {
    font-size: .9rem;
    padding: $nav-link-padding-y;

    &:not(:first-of-type) {
      padding: 1.7rem 1rem .5rem;
    }
  }
```

So the .nav-header only gets the 1rem for left and right if it is not the first-of-type.
