### ISSUE TITLE
Expandable Table

### ISSUE THREAD

**Issue by hkvstore** [ColorlibHQ/AdminLTE#3452]
In the Expandable Table example (https://github.com/ColorlibHQ/AdminLTE/blob/master/pages/tables/simple.html), the expandable row has ``class="expandable-body"`` but this is not considered in the ExpandableTable.js. I understand that that is for easier setup but having ``class="expandable-body"`` might be a good idea because it is possible that not every row has an expandable row. If there is no expandable row, we'll need to add a dummy blank row, it might be better if the expandable row is selected by a selector '.expandable-body', e.g. 

```js
/**
 * --------------------------------------------
 * AdminLTE ExpandableTable.js
 * License MIT
 * --------------------------------------------
 */

import $ from 'jquery'

/**
  * Constants
  * ====================================================
  */

const NAME = 'ExpandableTable'
const DATA_KEY = 'lte.expandableTable'
const EVENT_KEY = `.${DATA_KEY}`
const JQUERY_NO_CONFLICT = $.fn[NAME]

const EVENT_EXPANDED = `expanded${EVENT_KEY}`
const EVENT_COLLAPSED = `collapsed${EVENT_KEY}`

const SELECTOR_TABLE = '.expandable-table'
const SELECTOR_BODY = '.expandable-body'
const SELECTOR_DATA_TOGGLE = '[data-widget="expandable-table"]'
const SELECTOR_ARIA_ATTR = 'aria-expanded'

/**
  * Class Definition
  * ====================================================
  */
class ExpandableTable {
  constructor(element, options) {
    this._options = options
    this._element = element
  }

  // Public

  init() {
    $(SELECTOR_DATA_TOGGLE).each((_, $header) => {
      const $type = $($header).attr(SELECTOR_ARIA_ATTR)
      const $body = $($header).next(SELECTOR_BODY).children().first().children()
      if ($type === 'true') {
        $body.show()
      } else if ($type === 'false') {
        $body.hide()
        $body.parent().parent().addClass('d-none')
      }
    })
  }

  toggleRow() {
    const $element = this._element
    const time = 500
    const $type = $element.attr(SELECTOR_ARIA_ATTR)
    const $body = $element.next(SELECTOR_BODY).children().first().children()

    $body.stop()
    if ($type === 'true') {
      $body.slideUp(time, () => {
        $element.next(SELECTOR_BODY).addClass('d-none')
      })
      $element.attr(SELECTOR_ARIA_ATTR, 'false')
      $element.trigger($.Event(EVENT_COLLAPSED))
    } else if ($type === 'false') {
      $element.next(SELECTOR_BODY).removeClass('d-none')
      $body.slideDown(time)
      $element.attr(SELECTOR_ARIA_ATTR, 'true')
      $element.trigger($.Event(EVENT_EXPANDED))
    }
  }

  // Static

  static _jQueryInterface(operation) {
    return this.each(function () {
      let data = $(this).data(DATA_KEY)

      if (!data) {
        data = new ExpandableTable($(this))
        $(this).data(DATA_KEY, data)
      }

      if (typeof operation === 'string' && /init|toggleRow/.test(operation)) {
        data[operation]()
      }
    })
  }
}

/**
  * Data API
  * ====================================================
  */
$(SELECTOR_TABLE).ready(function () {
  ExpandableTable._jQueryInterface.call($(this), 'init')
})

$(document).on('click', SELECTOR_DATA_TOGGLE, function () {
  ExpandableTable._jQueryInterface.call($(this), 'toggleRow')
})

/**
  * jQuery API
  * ====================================================
  */

$.fn[NAME] = ExpandableTable._jQueryInterface
$.fn[NAME].Constructor = ExpandableTable
$.fn[NAME].noConflict = function () {
  $.fn[NAME] = JQUERY_NO_CONFLICT
  return ExpandableTable._jQueryInterface
}

export default ExpandableTable
```

**Comment by hkvstore** [comment]
Regarding CSS, currently the rotation of the caret is done by:
```css
[data-widget="expandable-table"] {
  cursor: pointer;

  i {
    transition: transform $transition-speed linear;
  }
  &[aria-expanded="true"] {
    td > i {
      // stylelint-disable selector-max-attribute
      &[class*="right"] {
        transform: rotate(90deg);
      }
      &[class*="left"] {
        transform: rotate(-90deg);
      }
      // stylelint-enable selector-max-attribute
    }
  }
}
```
While this works fine in the example, in the real cases the icon may not be a child in a table cell (``td > i``) , and there may be other icons in the row affected by above CSS. It is better if the selector ``i`` above has a class, e.g.
```css
[data-widget="expandable-table"] {
  cursor: pointer;

  i.expandable-caret {
    transition: transform $transition-speed linear;
  }
  &[aria-expanded="true"] {
    td i.expandable-caret {
      // stylelint-disable selector-max-attribute
      &[class*="right"] {
        transform: rotate(90deg);
      }
      &[class*="left"] {
        transform: rotate(-90deg);
      }
      // stylelint-enable selector-max-attribute
    }
  }
}

```
