### ISSUE TITLE
[BUG]: Sidebar search is hiding when hover triggered over sidebar-mini

### ISSUE THREAD

**Issue by Shidersz** [ColorlibHQ/AdminLTE#3597]
**Describe the bug**
The search bar of the sidebar is not showing when hover event is triggered over the sidebar and the **mini mode** is enabled. This is also and issue when you have `.sidebar-focused` class in the `aside` element, i.e, when you have clicked inside the sidebar after the previous hover event.

**To Reproduce**
1. Go to https://adminlte.io/themes/v3/index3.html
2. Click on the toggle button to get sidebar into the **mini mode**.
3. Move the mouse to the **mini sidebar** in order to auto expand it.
4. Check that the search bar is not visible

**Expected behavior**
The search bar should be visible when the mini sidebar is expanded. So you can click inside the search bar and correctly use it.

**Video**
You can see next video showing the issue:

https://user-images.githubusercontent.com/63609705/114774692-d0209580-9d46-11eb-8c9f-712d9b7e8f7d.mp4

**Environment (please complete the following information):**
- AdminLTE Version: v3.1.0
- Operating System: -
- Browser (Version): -

**Comment by danny007in** [comment]
its not bug
that is intentional for good UI experience

**Comment by Shidersz** [comment]
@danny007in So, if you want to start the panel with sidebar **collapse** and **sidebar mini** options, as shown on next image, you won't have a quick access to the search bar? You need to press the toggle button in order to access the search bar?

![Screenshot_2021-04-15 AdminLTE 3 Dashboard 3](https://user-images.githubusercontent.com/63609705/114878426-9eefa600-9dd6-11eb-9d28-e3dff008cb3b.png)

In my opinion, It will be a better UI experience to have a quick access to the search bar.

**Comment by Shidersz** [comment]
Maybe adding next style to [_sidebar-mini.scss](https://github.com/ColorlibHQ/AdminLTE/blob/master/build/scss/_sidebar-mini.scss) may help to improve this. I'm not sure since I do not have an environment to test these changes, but the `.nav-header` elements that are hiding on the **sidebar mini** mode are shown this way.

```scss
.sidebar-collapse {
  &.sidebar-mini,
  &.sidebar-mini-md,
  &.sidebar-mini-xs {
    .main-sidebar {
      ...
      &.sidebar-focused,
      &:hover {
        .nav-link {
          width: calc(#{$sidebar-width} - #{$sidebar-padding-x} * 2);
        }
        .nav-header {
          display: inline-block;
        }

        /* NEW STYLE */      
       .form-control-sidebar {
         display: inline-block;
       }
       .form-control-sidebar ~ .input-group-append {
         display: flex;
       }
       ...
```
