### ISSUE TITLE
[BUG] .navbar-expand-lg .navbar-nav .dropdown-menu rule not being triggered

### ISSUE THREAD

**Issue by mcpherson-enterprises** [ColorlibHQ/AdminLTE#3604]
**Describe the bug**
The _navbar.scss file, on line 133-134, says "Generate series of 'navbar-expand-*' responsive classes for configuring where your navbar collapses"

Then the following code includes:

```scss
.navbar-expand {
  @each $breakpoint in map-keys($grid-breakpoints) {
    $next: breakpoint-next($breakpoint, $grid-breakpoints);
    $infix: breakpoint-infix($next, $grid-breakpoints);

    &#{$infix} {
      @include media-breakpoint-down($breakpoint) {
        > .container,
        > .container-fluid {
          padding-right: 0;
          padding-left: 0;
        }
      }

      @include media-breakpoint-up($next) {
        flex-flow: row nowrap;
        justify-content: flex-start;

        .navbar-nav {
          flex-direction: row;

          .dropdown-menu {
            position: absolute;
          }

          .nav-link {
            padding-right: $navbar-nav-link-padding-x;
            padding-left: $navbar-nav-link-padding-x;
          }
        }

        // For nesting containers, have to redeclare for alignment purposes
        > .container,
        > .container-fluid {
          flex-wrap: nowrap;
        }

        .navbar-collapse {
          display: flex !important; // stylelint-disable-line declaration-no-important

          // Changes flex-bases to auto because of an IE10 bug
          flex-basis: auto;
        }

        .navbar-toggler {
          display: none;
        }
      }
    }
  }
}
```
However, the collapse break-point versions of the navbar-expand class (i.e. .navbar-expand-lg) are not triggering this rule. Only the .navbar-expand class is.

**To Reproduce**
1. Go to AdminLTE demo page (https://adminlte.io/themes/dev/AdminLTE/index.html)
2. Right-click the top nav menu and select "Inspect Element" to bring up the inspector
3. Change the screen size to tablet/IPad or Mobile screen size
4. Click on the notification (bell) icon to invoke the drop-down menu (see Expected behavior screenshot)
5. Right-click the top nav menu and select "Inspect Element" to bring up the inspector
6. Find the `<nav class="main-header navbar navbar-expand navbar-white navbar-light>` element and change "navbar-expand" to "navbar-expand-lg"
7. Click on the notification (bell) icon to invoke the drop-down menu
8. The drop-down expands the top menu (see Actual behavior screenshot)

**Expected behavior**
The drop-down menu would extend down past the border of the top menu (i.e. the drop-down menu would have a position: absolute rule applied)

**Screenshots**
Expected behavior:
![image](https://user-images.githubusercontent.com/61546085/115146682-80cbb500-a025-11eb-82cb-16d317222f66.png)

Actual behavior:
![image](https://user-images.githubusercontent.com/61546085/115146705-99d46600-a025-11eb-93b5-4b31dc72fb42.png)

**Environment (please complete the following information):**
- AdminLTE Version: v3.0.2
- Operating System:  Windows 10
- Browser (Version): Firefox (latest)

**Additional context**
