### ISSUE TITLE
[BUG] v4.x main sidebar icon, text spacing

### ISSUE THREAD

**Issue by umer936** [ColorlibHQ/AdminLTE#4140]
We've been using the 4.x branch of AdminLTE and found that on the sidebar, the icon does not keep a fixed width. 
This means icons of different sizes make the link text not be aligned. I was able to trace it to this CSS property that is in AdminLTE 3.1 (main-sidebar.scss:123), but not in AdminLTE 4: 
```css
.nav-sidebar > .nav-item .nav-icon {
    width: 1.6rem;
}
```

I went ahead and added it to my own CSS file, but it should probably be in the main-sidebar.scss (or nav-sidebar.scss) file for AdminLTE 4.
