### ISSUE TITLE
Mobile sidebar behaviour on desktop layout

### ISSUE THREAD

**Issue by HermesTAS** [ColorlibHQ/AdminLTE#4856]
i can't find a forum of adminLTE, so i'm gonna ask here.

i'm using version 3.2.0

i want to use mobile sidebar behaviour on desktop layout
here are my goals on desktop layout:
- `sidebar will fully closed` instead of showiaaang mini sidebar
- `content wrapper will stacked behind the sidebar` instead of moving right 250px
- `sidebar overlay will appear`

is there documented way to do this?
or do i need to override some codes?

Thanks.

**Comment by REJack** [comment]
You can simply achieve this by removing the `sidebar-mini`-class from `<body>` and adding this css classes (after AdminLTE's css files itself).

```css
.content-wrapper,
.main-header,
.main-footer {
  margin-left: 0 !important;
}
body:not(.sidebar-collapse) #sidebar-overlay {
  display: block;
}
```
