### ISSUE TITLE
[BUG] Wrong display when no content

### ISSUE THREAD

**Issue by Safranil** [ColorlibHQ/AdminLTE#5636]
**Describe the bug**
When the content in `main.app-main` is not long enough or without explicit size, the layout is broken on small screen.

After some digging, this is because `.app-wrapper` have `grid-template-columns: auto 1fr;`, the `auto` get the content size wrong in this case.

**Patch**
```scss
.app-main-wrapper {
  @include media-breakpoint-down(lg) {
    width: 100vw;
  }
}
```

**Screenshots**
Before the patch:
![image](https://github.com/user-attachments/assets/e4604973-56db-44e5-b045-0b135f1d436a)

After the patch:
![image](https://github.com/user-attachments/assets/6f648989-3e58-40dc-a719-ef27627f098c)

**Environment (please complete the following information):**
- AdminLTE Version: 4.0.0-beta1
- Operating System:  Debian 12
- Browser (Version): Firefox 115.13.0 ESR
